spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Alibou
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: alibou-rest-api
      principle-attribute: preferred_username
